"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.titanic = exports.tiburon = void 0;
var movie_1 = require("./movie");
var professional_1 = require("./professional");
var will = new professional_1.Professional("Will Smith", 54, 80, 1.88, false, "americano", 4, "Actor");
var spielberg = new professional_1.Professional("Steven Spielberg", 74, 70, 1.72, true, "americano", 50, "Director");
var penelope = new professional_1.Professional("Penelope Cruz", 48, 70, 1.69, false, "espaniola", 1, "Actriz");
exports.tiburon = new movie_1.Movie("Tiburon", 1980, "EEUU", "Terror");
exports.tiburon.director = spielberg;
exports.tiburon.actors = [will, penelope];
exports.tiburon.writer = spielberg;
exports.tiburon.language = "Ingles";
exports.tiburon.plataforma = "Planet";
exports.tiburon.isMCU = true;
exports.tiburon.mainCharacterName = "Jose";
exports.tiburon.producer = "Camilo Mena";
exports.tiburon.distributor = "Netflix";
exports.tiburon.plataforma = "Neox";
exports.titanic = new movie_1.Movie("Titanic", 1997, "EEUU", "Drama");
exports.titanic.director = spielberg;
exports.titanic.actors = [will, penelope];
exports.titanic.writer = spielberg;
exports.titanic.language = "Ingles";
exports.titanic.plataforma = "Planet";
exports.titanic.isMCU = true;
exports.titanic.mainCharacterName = "Jose";
exports.titanic.producer = "Camilo Mena";
exports.titanic.distributor = "Netflix";
exports.titanic.plataforma = "Neox";
exports.tiburon.print();
exports.titanic.print();
